/**
 * Author:  BelkinSergei
 * Created: 03.02.2019
 */

INSERT INTO AGENCY( ID, AGENCY_NAME ) VALUES( 17, 'ФСПП' );
INSERT INTO AGENCY( ID, AGENCY_NAME ) VALUES( 39, 'ФНС' );
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, CONVERSION_PATTERN, MATCH_PATTERN, AGENCY, CONVERSION_TYPE )
VALUES (21, 'Паспорт РФ', 'SS SS NNNNNN', '^\d{2} \d{2} \d{6}$', 39, 0);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, CONVERSION_PATTERN, MATCH_PATTERN, AGENCY, CONVERSION_TYPE )
VALUES (22, 'Загранпаспорт РФ', 'SS NNNNNN', '^\d{2} \d{6}$', 39, 1);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, CONVERSION_PATTERN, MATCH_PATTERN, AGENCY, CONVERSION_TYPE )
VALUES (70, 'Паспорт РФ', 'NNNNNN-SSSS', '^\d{6}-\d{4}$', 17, 0);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, CONVERSION_PATTERN, MATCH_PATTERN, AGENCY, CONVERSION_TYPE )
VALUES (80, 'Загранпаспорт РФ', 'NNNNNN.SS', '^\d{6}\.\d{2}$', 17, 1);

-- test values

INSERT INTO CLIENT( ID, LASTNAME, FIRSTNAME, DOCTYPE, NUMBERSERIES )
VALUES( 232, 'Petrov', 'Petr', 0, '123456 12 12' );
INSERT INTO CLIENT( ID, LASTNAME, FIRSTNAME, DOCTYPE, NUMBERSERIES )
VALUES( 76, 'Ivanov', 'Ivan', 1, '123456 12' );
INSERT INTO CLIENT( ID, LASTNAME, FIRSTNAME, DOCTYPE, NUMBERSERIES )
VALUES( 195, 'Name', 'Name', 0, '999888 00 11' );