/**
 * Author:  BelkinSergei
 * Created: 03.02.2019
 */

INSERT INTO AGENCY( ID, AGENCY_NAME ) VALUES( 17, 'ФСПП' );
INSERT INTO AGENCY( ID, AGENCY_NAME ) VALUES( 39, 'ФНС' );
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, PATTERN, MATCHPATTERN, AGENCY, CONVERSION_TYPE )
VALUES (21, 'Паспорт РФ', 'SS SS NNNNNN', '^\d{2} \d{2} \d{6}$', 39, 0);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, PATTERN, MATCHPATTERN, AGENCY, CONVERSION_TYPE )
VALUES (22, 'Загранпаспорт РФ', 'SS NNNNNN', '^\d{2} \d{6}$', 39, 1);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, PATTERN, MATCHPATTERN, AGENCY, CONVERSION_TYPE )
VALUES (70, 'Паспорт РФ', 'NNNNNN-SSSS', '^\d{6}-\d{4}$', 17, 0);
INSERT INTO CERTIFICATE( ID, CERTIFICATE_NAME, PATTERN, MATCHPATTERN, AGENCY, CONVERSION_TYPE )
VALUES (80, 'Загранпаспорт РФ', 'NNNNNN.SS', '^\d{6}\.\d{2}$', 17, 1);